name: Build Skia Prebuilts For Skiko (RISC-V64)

on:
  push:
    branches:
      - riscv64

permissions:
  contents: read

jobs:
  linux-riscv64:
    runs-on: [self-hosted, linux, riscv64]
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Linux RISC-V64 build dependencies
        run: sudo ./tools/skia_release/prepare_linux_riscv64.sh

      - id: version
        shell: bash
        run: |
          SHA="$(git rev-parse --short=10 "$GITHUB_SHA")"
          echo "value=dev-${SHA}" >> "$GITHUB_OUTPUT"

      - run: python3 tools/skia_release/build.py --skia-dir . --build-type ${{ matrix.build_type }} --target linux --machine riscv64 --gpu-as-extension --enable-graphite
      - run: python3 tools/skia_release/archive.py --skia-dir . --version ${{ steps.version.outputs.value }} --build-type ${{ matrix.build_type }} --target linux --machine riscv64
